import GINSHTForm from './GINSHTForm';
const {
    formField: {
        empleado,
        empresa,
        centroDeTrabajo,
        puestoDeTrabajo,
        fecha,
        referencia,
        datosDeElevacion,
        datosDeTransporte,
        pesoRealManejado,
        pesoTeoricoRecomendado,
        duracionTarea,
        posturaLevantamiento,
        alturaLevantamiento,
        separacionLevantamiento,
        desplazamientoVertical,
        giroDelTronco,
        tipoDeAgarre,
        duracionManipulacion,
        frecuenciaDeManipulacion,
        valorFinalFrecuencia,
        pesoAceptable,
        indiceRiesgoElevacion,
        indiceRiesgoTransporte,
        numeroDeDesplazamientos,
        distanciaDeDesplazamientos,
        listaDeFactoresPuesto, 
        listaDeFactoresTrabajador,
        indicaciones
    }
} = GINSHTForm;

export default {
    [empleado.name]: '',
    [empresa.name]: '',
    [centroDeTrabajo.name]: '',
    [puestoDeTrabajo.name]: '',
    [fecha.name]: '',
    [referencia.name]: '',
    [datosDeElevacion.name]: '',
    [datosDeTransporte.name]: '',
    [pesoRealManejado.name]: '',
    [pesoTeoricoRecomendado.name]: '',
    [duracionTarea.name]: '',
    [posturaLevantamiento.name]: '',
    [alturaLevantamiento.name]: '2',
    [separacionLevantamiento.name]: '0',
    [desplazamientoVertical.name]: '',
    [giroDelTronco.name]: '',
    [tipoDeAgarre.name]: '',
    [duracionManipulacion.name]: '',
    [frecuenciaDeManipulacion.name]: '',
    [valorFinalFrecuencia.name]: '',
    [pesoAceptable.name]: '',
    [indiceRiesgoElevacion.name]: '',  
    [indiceRiesgoTransporte.name]: '',  
    [numeroDeDesplazamientos.name]: '',
    [distanciaDeDesplazamientos.name]: '',
    [listaDeFactoresPuesto.name]: [],
    [listaDeFactoresTrabajador.name]: [],
    [indicaciones.name]: ''
}