import GINSHTForm from './GINSHTForm';
const {
    formField: {
        empleado,
        empresa,
        centroDeTrabajo,
        puestoDeTrabajo,
        fecha,
        referencia,
        datosDeElevacion,
        datosDeTransporte,
        pesoRealManejado,
        pesoTeoricoRecomendado,
        duracionTarea,
        posturaLevantamiento,
        alturaLevantamiento,
        separacionLevantamiento,
        desplazamientoVertical,
        giroDelTronco,
        tipoDeAgarre,
        duracionManipulacion,
        frecuenciaDeManipulacion,
        valorFinalFrecuencia,
        pesoAceptable,
        indiceRiesgoElevacion,
        indiceRiesgoTransporte,
        numeroDeDesplazamientos,
        distanciaDeDesplazamientos,
        listaDeFactoresPuesto, 
        listaDeFactoresTrabajador,
        indicaciones,
        images
    }
} = GINSHTForm;

export default {
    [empleado.name]: '',
    [empresa.name]: '',
    [centroDeTrabajo.name]: '',
    [puestoDeTrabajo.name]: '',
    [fecha.name]: '',
    [referencia.name]: '',
    [datosDeElevacion.name]: '',
    [datosDeTransporte.name]: '',
    [pesoRealManejado.name]: 0,
    [pesoTeoricoRecomendado.name]: 0,
    [duracionTarea.name]: 0,
    [posturaLevantamiento.name]: 0,
    [alturaLevantamiento.name]: 0,
    [separacionLevantamiento.name]: 0,
    [desplazamientoVertical.name]: 0,
    [giroDelTronco.name]: 0,
    [tipoDeAgarre.name]: 0,
    [duracionManipulacion.name]: 0,
    [frecuenciaDeManipulacion.name]: 0,
    [valorFinalFrecuencia.name]: 0,
    [pesoAceptable.name]: 0,
    [indiceRiesgoElevacion.name]: 0,  
    [indiceRiesgoTransporte.name]: 0,  
    [numeroDeDesplazamientos.name]: 0,
    [distanciaDeDesplazamientos.name]: 0,
    [listaDeFactoresPuesto.name]: [],
    [listaDeFactoresTrabajador.name]: [],
    [indicaciones.name]: '',
    [images]: []
}