name: Node.js Deployment

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Set the Node.js version

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Build
      run: npm run build # If your project needs a build step

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.13.15 # This action simplifies Heroku deployment
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "PreventAI" # Replace with your Heroku app name
        heroku_email: "sergio.rodriguezvazquez@alum.uca.es" # Replace with your Heroku account email
